version: '3.8'

services:
  iperf-armv7:
    build:
      context: .
      dockerfile: Dockerfile.armv7
      platforms:
        - linux/arm/v7
    ports:
      - "8080:8080"
      - "5201:5201"
    environment:
      - HOSTNAME=iperf-armv7
      - IPERF_PORT=5201
      - WEB_PORT=8080
      - DISCOVERY_INTERVAL=30
      - HISTORY_RETENTION=30
    volumes:
      - iperf_data_armv7:/app/data
    restart: unless-stopped
    networks:
      - iperf_network

volumes:
  iperf_data_armv7:
    driver: local

networks:
  iperf_network:
    driver: bridge
