version: '3.8'

services:
  iperf-web-1:
    build: .
    ports:
      - "8080:8080"
      - "5201:5201"
    environment:
      - HOSTNAME=iperf-node-1
      - IPERF_PORT=5201
      - WEB_PORT=8080
      - DISCOVERY_INTERVAL=30
      - HISTORY_RETENTION=30
    volumes:
      - ./data1:/app/data
    restart: unless-stopped
    networks:
      - iperf-network

  iperf-web-2:
    build: .
    ports:
      - "8081:8080"
      - "5202:5201"
    environment:
      - HOSTNAME=iperf-node-2
      - IPERF_PORT=5201
      - WEB_PORT=8080
      - DISCOVERY_INTERVAL=30
      - HISTORY_RETENTION=30
    volumes:
      - ./data2:/app/data
    restart: unless-stopped
    networks:
      - iperf-network

networks:
  iperf-network:
    driver: bridge